import type { Component } from 'vue'
import {
  Baby,
  Balloon,
  Banknote,
  Beer,
  BicepsFlexed,
  Bike,
  Blender,
  Book,
  Brain,
  BrickWallShield,
  Briefcase,
  BrushCleaning,
  Bubbles,
  Bus,
  Camera,
  Car,
  CarTaxiFront,
  ChessKnight,
  CircleDollarSign,
  CircleParking,
  Coffee,
  Coins,
  CookingPot,
  CreditCard,
  CupSoda,
  Dessert,
  Dices,
  Dog,
  Drill,
  Droplet,
  Drum,
  Dumbbell,
  FerrisWheel,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  Guitar,
  HandHeart,
  HandHelping,
  HandMetal,
  HandPlatter,
  Handshake,
  Heart,
  House,
  IceCreamBowl,
  Landmark,
  Laptop,
  Laugh,
  Luggage,
  MicVocal,
  Mountain,
  Mouse,
  Music,
  Music4,
  Paintbrush,
  Palette,
  PartyPopper,
  PawPrint,
  Phone,
  Piano,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Popcorn,
  Presentation,
  Puzzle,
  Receipt,
  Refrigerator,
  Repeat,
  Salad,
  Scissors,
  Ship,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  SmilePlus,
  SoapDispenserDroplet,
  Sparkles,
  Speech,
  Sprout,
  SquareParking,
  Stethoscope,
  Tag,
  TagX,
  Telescope,
  Theater,
  ToolCase,
  TramFront,
  TreePalm,
  TrendingUp,
  Tv,
  Utensils,
  Volleyball,
  Wallet,
  WashingMachine,
  WavesHorizontal,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from '@lucide/vue'
import type { CategoryType } from '~/types/category'

export const categoryIconMap: Record<string, Component> = {
  baby: Baby,
  balloon: Balloon,
  banknote: Banknote,
  beer: Beer,
  'biceps-flexed': BicepsFlexed,
  bike: Bike,
  blender: Blender,
  book: Book,
  brain: Brain,
  'brick-wall-shield': BrickWallShield,
  briefcase: Briefcase,
  'brush-cleaning': BrushCleaning,
  bubbles: Bubbles,
  bus: Bus,
  camera: Camera,
  car: Car,
  'car-taxi-front': CarTaxiFront,
  'chess-knight': ChessKnight,
  'circle-dollar': CircleDollarSign,
  'circle-parking': CircleParking,
  coffee: Coffee,
  coins: Coins,
  'cooking-pot': CookingPot,
  'credit-card': CreditCard,
  'cup-soda': CupSoda,
  dessert: Dessert,
  dices: Dices,
  dog: Dog,
  drill: Drill,
  droplet: Droplet,
  drum: Drum,
  dumbbell: Dumbbell,
  'ferris-wheel': FerrisWheel,
  film: Film,
  flame: Flame,
  footprints: Footprints,
  fuel: Fuel,
  gamepad: Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  guitar: Guitar,
  'hand-heart': HandHeart,
  'hand-helping': HandHelping,
  'hand-metal': HandMetal,
  'hand-platter': HandPlatter,
  handshake: Handshake,
  heart: Heart,
  house: House,
  'ice-cream-bowl': IceCreamBowl,
  landmark: Landmark,
  laptop: Laptop,
  laugh: Laugh,
  luggage: Luggage,
  'mic-vocal': MicVocal,
  mountain: Mountain,
  mouse: Mouse,
  music: Music,
  'music-4': Music4,
  paintbrush: Paintbrush,
  palette: Palette,
  parking: SquareParking,
  party: PartyPopper,
  'paw-print': PawPrint,
  phone: Phone,
  piano: Piano,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  popcorn: Popcorn,
  presentation: Presentation,
  puzzle: Puzzle,
  receipt: Receipt,
  refrigerator: Refrigerator,
  repeat: Repeat,
  salad: Salad,
  scissors: Scissors,
  ship: Ship,
  shirt: Shirt,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  'smile-plus': SmilePlus,
  'soap-dispenser': SoapDispenserDroplet,
  sparkles: Sparkles,
  speech: Speech,
  sprout: Sprout,
  stethoscope: Stethoscope,
  tag: Tag,
  'tag-x': TagX,
  telescope: Telescope,
  theater: Theater,
  'tool-case': ToolCase,
  'tram-front': TramFront,
  'tree-palm': TreePalm,
  'trending-up': TrendingUp,
  tv: Tv,
  utensils: Utensils,
  volleyball: Volleyball,
  wallet: Wallet,
  'washing-machine': WashingMachine,
  'waves-horizontal': WavesHorizontal,
  wheat: Wheat,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
}

export const categoryIconNames = Object.keys(categoryIconMap)

export function categoryIcon(name: string): Component {
  return categoryIconMap[name] ?? Tag
}

/** A paleta de cor mora em utils/categoryPalette.ts — só cores do Akoma. */

export const categoryTypeOptions: { value: CategoryType; label: string }[] = [
  { value: 'expense', label: 'Despesa' },
  { value: 'income', label: 'Receita' },
  { value: 'transfer', label: 'Transferência' },
]

export const categoryTypeLabels: Record<CategoryType, string> = {
  expense: 'Despesa',
  income: 'Receita',
  transfer: 'Transferência',
}
