import type { Component } from 'vue'
import {
  Baby,
  Banknote,
  Beer,
  Book,
  Brain,
  Briefcase,
  Bubbles,
  Bus,
  Car,
  CircleDollarSign,
  Coffee,
  Coins,
  CreditCard,
  Dog,
  Droplet,
  Dumbbell,
  Film,
  Flame,
  Footprints,
  Fuel,
  Gamepad2,
  Gift,
  GraduationCap,
  HandHeart,
  Handshake,
  Heart,
  House,
  Landmark,
  Laptop,
  Music,
  PartyPopper,
  Phone,
  PiggyBank,
  Pill,
  Pizza,
  Plane,
  Receipt,
  Refrigerator,
  Repeat,
  Scissors,
  Shirt,
  SoapDispenserDroplet,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  SquareParking,
  Stethoscope,
  Tag,
  TrendingUp,
  Tv,
  Utensils,
  Wallet,
  Wheat,
  Wifi,
  Wine,
  Wrench,
  Zap,
} from '@lucide/vue'
import type { CategoryType } from '~/types/category'

export const categoryIconMap: Record<string, Component> = {
  baby: Baby,
  banknote: Banknote,
  beer: Beer,
  book: Book,
  brain: Brain,
  briefcase: Briefcase,
  bubbles: Bubbles,
  bus: Bus,
  car: Car,
  'circle-dollar': CircleDollarSign,
  coffee: Coffee,
  coins: Coins,
  'credit-card': CreditCard,
  dog: Dog,
  droplet: Droplet,
  dumbbell: Dumbbell,
  film: Film,
  flame: Flame,
  footprints: Footprints,
  fuel: Fuel,
  gamepad: Gamepad2,
  gift: Gift,
  'graduation-cap': GraduationCap,
  'hand-heart': HandHeart,
  handshake: Handshake,
  heart: Heart,
  house: House,
  landmark: Landmark,
  laptop: Laptop,
  music: Music,
  parking: SquareParking,
  party: PartyPopper,
  phone: Phone,
  'piggy-bank': PiggyBank,
  pill: Pill,
  pizza: Pizza,
  plane: Plane,
  receipt: Receipt,
  refrigerator: Refrigerator,
  repeat: Repeat,
  scissors: Scissors,
  shirt: Shirt,
  'soap-dispenser': SoapDispenserDroplet,
  'shopping-bag': ShoppingBag,
  'shopping-cart': ShoppingCart,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  tag: Tag,
  'trending-up': TrendingUp,
  tv: Tv,
  utensils: Utensils,
  wallet: Wallet,
  wheat: Wheat,
  wifi: Wifi,
  wine: Wine,
  wrench: Wrench,
  zap: Zap,
}

export const categoryIconNames = Object.keys(categoryIconMap)

export function categoryIcon(name: string): Component {
  return categoryIconMap[name] ?? Tag
}

/** A paleta de cor mora em utils/categoryPalette.ts — só cores do Akoma. */

export const categoryTypeOptions: { value: CategoryType; label: string }[] = [
  { value: 'expense', label: 'Despesa' },
  { value: 'income', label: 'Receita' },
  { value: 'transfer', label: 'Transferência' },
]

export const categoryTypeLabels: Record<CategoryType, string> = {
  expense: 'Despesa',
  income: 'Receita',
  transfer: 'Transferência',
}
